// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from 'libs/stimulus'


import Bridge__FormController from 'controllers/bridge/form_controller'
Stimulus.register('bridge--form', Bridge__FormController)

import DateFilterController from 'controllers/date_filter_controller'
Stimulus.register('date-filter', DateFilterController)

import InlineEditController from 'controllers/inline_edit_controller'
Stimulus.register('inline-edit', InlineEditController)

import KeyboardShortcutsController from 'controllers/keyboard_shortcuts_controller'
Stimulus.register('keyboard-shortcuts', KeyboardShortcutsController)

import MobileMenuController from 'controllers/mobile_menu_controller'
Stimulus.register('mobile-menu', MobileMenuController)

import PasswordRevealController from 'controllers/password_reveal_controller'
Stimulus.register('password-reveal', PasswordRevealController)

import SearchClientsController from 'controllers/search_clients_controller'
Stimulus.register('search-clients', SearchClientsController)

import SearchProjectsController from 'controllers/search_projects_controller'
Stimulus.register('search-projects', SearchProjectsController)

import SessionRecoveryController from 'controllers/session_recovery_controller'
Stimulus.register('session-recovery', SessionRecoveryController)

import SubdomainPreviewController from 'controllers/subdomain_preview_controller'
Stimulus.register('subdomain-preview', SubdomainPreviewController)

import TimerController from 'controllers/timer_controller'
Stimulus.register('timer', TimerController)
